<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

if (!function_exists('get_patient_tabs')) {
    function get_patient_tabs($id = null)
    {
        return [
            'index' => [
                'slug' => 'index',
                'name' => 'Overview',
                'icon' => 'fa fa-user',
                'view' => 'admin/patient/groups/overview',
                'position' => 1,
                'badge' => [],
                'href' => admin_url('patient'),
                'children' => [],
            ],
            'details' => [
                'slug' => 'details',
                'name' => 'Details',
                'icon' => 'fa fa-id-card',
                'view' => 'admin/patient/groups/details',
                'position' => 2,
                'badge' => [],
                'href' => admin_url('patient/details'),
                'children' => [],
            ],
            'notes' => [
                'slug' => 'notes',
                'name' => _l('contracts_notes_tab'),
                'icon' => 'fa-regular fa-note-sticky',
                'view' => 'admin/patient/groups/notes',
                'position' => 3,
                'badge' => [],
                'href' => admin_url('patient/notes'),
                'children' => [],
            ],
            'invoices' => [
                'slug' => 'invoices',
                'name' => _l('client_invoices_tab'),
                'icon' => 'fa fa-file-text',
                'view' => 'admin/patient/groups/invoices',
                'position' => 4,
                'badge' => [],
                'href' => admin_url('patient/invoices'),
                'children' => [],
            ],
            'payments' => [
                'slug' => 'payments',
                'name' => _l('client_payments_tab'),
                'icon' => 'fa fa-line-chart',
                'view' => 'admin/patient/groups/payments',
                'position' => 5,
                'badge' => [],
                'href' => admin_url('patient/payments'),
                'children' => [],
            ],
            'estimates' => [
                'slug' => 'estimates',
                'name' => _l('estimates'),
                'icon' => 'fa-regular fa-file',
                'view' => 'admin/patient/groups/estimates',
                'position' => 6,
                'badge' => [],
                'href' => admin_url('patient/estimates'),
                'children' => [],
            ],
            'projects' => [
                'slug' => 'projects',
                'name' => _l('projects'),
                'icon' => 'fa-solid fa-chart-gantt',
                'view' => 'admin/patient/groups/projects',
                'position' => 7,
                'badge' => [],
                'href' => admin_url('patient/projects'),
                'children' => [],
            ],
            'tasks' => [
                'slug' => 'tasks',
                'name' => _l('tasks'),
                'icon' => 'fa-regular fa-circle-check',
                'view' => 'admin/patient/groups/tasks',
                'position' => 8,
                'badge' => [],
                'href' => admin_url('patient/tasks'),
                'children' => [],
            ],
            'tickets' => [
                'slug' => 'tickets',
                'name' => _l('tickets'),
                'icon' => 'fa-regular fa-life-ring',
                'view' => 'admin/patient/groups/tickets',
                'position' => 9,
                'badge' => [],
                'href' => admin_url('patient/tickets'),
                'children' => [],
            ],
            'attachments' => [
                'slug' => 'attachments',
                'name' => _l('customer_attachments'),
                'icon' => 'fa fa-paperclip',
                'view' => 'admin/patient/groups/attachments',
                'position' => 10,
                'badge' => [],
                'href' => admin_url('patient/attachments'),
                'children' => [],
            ],
            'reminders' => [
                'slug' => 'reminders',
                'name' => _l('reminders'),
                'icon' => 'fa-regular fa-bell',
                'view' => 'admin/patient/groups/reminders',
                'position' => 11,
                'badge' => [],
                'href' => admin_url('patient/reminders'),
                'children' => [],
            ],
            'map' => [
                'slug' => 'map',
                'name' => _l('customer_map'),
                'icon' => 'fa-solid fa-location-dot',
                'view' => 'admin/patient/groups/map',
                'position' => 12,
                'badge' => [],
                'href' => admin_url('patient/map'),
                'children' => [],
            ],
            'medicine' => [
                'slug' => 'medicine',
                'name' => _l('medicine'),
                'icon' => 'fa-solid fa-plus',
                'view' => 'admin/patient/groups/medicine',
                'position' => 13,
                'badge' => [],
                'href' => admin_url('patient/medicine'),
                'children' => [],
            ],
        ];
    }

}

